-- AlterTable
ALTER TABLE "Department" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(4),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(4);

-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(4),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(4);
